const BuildingChina = {
    防: ["值", "捕", "永和"],
    防护: ["值更房", "捕快房", "永和堂"],
    住宅: [
        {
            name: "普通住宅",
            text: "宅",
            size: 1,
            range_size: 0,
            color: "#000000",
            background_color: "#FFA500",
            border_color: "#000000",
        },
        {
            name: "高级住宅",
            text: "高级住宅",
            size: 3,
            range_size: 0,
            color: "#000000",
            background_color: "#FFA500",
            border_color: "#000000",
        },
    ],
    农业: [
        {
            name: "水稻田",
            text: "水稻田",
            size: 5,
            range_size: 0,
            color: "#000000",
            background_color: "#32ff7e",
            border_color: "#000000",
        },
        {
            name: "白菜地",
            text: "白菜地",
            size: 3,
            range_size: 0,
            color: "#000000",
            background_color: "#32ff7e",
            border_color: "#000000",
        },
        {
            name: "梨园",
            text: "梨园",
            size: 3,
            range_size: 0,
            color: "#000000",
            background_color: "#32ff7e",
            border_color: "#000000",
        },
        {
            name: "猎户小屋",
            text: "猎户",
            size: 2,
            range_size: 0,
            color: "#000000",
            background_color: "#32ff7e",
            border_color: "#000000",
        },
        {
            name: "高粱地",
            text: "高粱地",
            size: 3,
            range_size: 0,
            color: "#000000",
            background_color: "#32ff7e",
            border_color: "#000000",
        },
        {
            name: "茶树小屋",
            text: "茶树小屋",
            size: 4,
            range_size: 0,
            color: "#000000",
            background_color: "#32ff7e",
            border_color: "#000000",
        },
        {
            name: "养蚕小屋",
            text: "养蚕小屋",
            size: 3,
            range_size: 0,
            color: "#000000",
            background_color: "#32ff7e",
            border_color: "#000000",
        },
    ],
    工业: [
        {
            name: "瓦窑",
            text: "瓦窑",
            size: 2,
            range_size: 0,
            color: "#000000",
            background_color: "#40E0D0",
            border_color: "#000000",
        },
        {
            name: "砖窑",
            text: "砖窑",
            size: 2,
            range_size: 0,
            color: "#000000",
            background_color: "#40E0D0",
            border_color: "#000000",
        },
        {
            name: "炼铜厂",
            text: "炼铜厂",
            size: 2,
            range_size: 0,
            color: "#000000",
            background_color: "#40E0D0",
            border_color: "#000000",
        },
        {
            name: "瓷器场",
            text: "瓷器场",
            size: 2,
            range_size: 0,
            color: "#000000",
            background_color: "#40E0D0",
            border_color: "#000000",
        },
        {
            name: "铜器厂",
            text: "铜器厂",
            size: 2,
            range_size: 0,
            color: "#000000",
            background_color: "#40E0D0",
            border_color: "#000000",
        },
        {
            name: "酒厂",
            text: "酒厂",
            size: 3,
            range_size: 0,
            color: "#000000",
            background_color: "#40E0D0",
            border_color: "#000000",
        },
        {
            name: "造纸厂",
            text: "造纸厂",
            size: 3,
            range_size: 0,
            color: "#000000",
            background_color: "#40E0D0",
            border_color: "#000000",
        },
        {
            name: "染坊",
            text: "染坊",
            size: 3,
            range_size: 0,
            color: "#000000",
            background_color: "#40E0D0",
            border_color: "#000000",
        },
    ],
    商业: [
        {
            name: "粮店",
            text: "粮",
            size: 1,
            range_size: 5,
            color: "#000000",
            background_color: "#FFEC8B",
            border_color: "#000000",
        },
        {
            name: "蔬菜摊",
            text: "菜",
            size: 1,
            range_size: 5,
            color: "#000000",
            background_color: "#FFEC8B",
            border_color: "#000000",
        },
        {
            name: "水果摊",
            text: "果",
            size: 1,
            range_size: 5,
            color: "#000000",
            background_color: "#FFEC8B",
            border_color: "#000000",
        },
        {
            name: "肉铺",
            text: "肉",
            size: 1,
            range_size: 5,
            color: "#000000",
            background_color: "#FFEC8B",
            border_color: "#000000",
        },
        {
            name: "鱼摊",
            text: "鱼",
            size: 1,
            range_size: 5,
            color: "#000000",
            background_color: "#FFEC8B",
            border_color: "#000000",
        },
        {
            name: "瓷器店",
            text: "瓷",
            size: 1,
            range_size: 5,
            color: "#000000",
            background_color: "#FFEC8B",
            border_color: "#000000",
        },
        {
            name: "铜器店",
            text: "铜",
            size: 1,
            range_size: 5,
            color: "#000000",
            background_color: "#FFEC8B",
            border_color: "#000000",
        },
        {
            name: "酒馆",
            text: "酒",
            size: 1,
            range_size: 5,
            color: "#000000",
            background_color: "#FFEC8B",
            border_color: "#000000",
        },
        {
            name: "纸墨轩",
            text: "纸",
            size: 1,
            range_size: 5,
            color: "#000000",
            background_color: "#FFEC8B",
            border_color: "#000000",
        },
        {
            name: "茶馆",
            text: "茶",
            size: 1,
            range_size: 5,
            color: "#000000",
            background_color: "#FFEC8B",
            border_color: "#000000",
        },
        {
            name: "丝绸店",
            text: "绸",
            size: 1,
            range_size: 5,
            color: "#000000",
            background_color: "#FFEC8B",
            border_color: "#000000",
        },
    ],
    市政: [
        {
            name: "水井",
            text: "水",
            size: 1,
            range_size: 4,
            color: "#000000",
            background_color: "#1E90FF",
            border_color: "#000000",
        },
        {
            name: "值更房",
            text: "值",
            size: 1,
            range_size: 6,
            color: "#000000",
            background_color: "#FF0000",
            border_color: "#000000",
        },
        {
            name: "捕快房",
            text: "捕",
            size: 1,
            range_size: 6,
            color: "#000000",
            background_color: "#FF0000",
            border_color: "#000000",
        },
        {
            name: "永和堂",
            text: "永和",
            size: 2,
            range_size: 7,
            color: "#000000",
            background_color: "#FF0000",
            border_color: "#000000",
        },
        {
            name: "粮仓",
            text: "粮仓",
            size: 2,
            range_size: 0,
            color: "#000000",
            background_color: "#98F5FF",
            border_color: "#000000",
        },
        {
            name: "货栈",
            text: "货栈",
            size: 4,
            range_size: 0,
            color: "#000000",
            background_color: "#98F5FF",
            border_color: "#000000",
        },
        {
            name: "皇宫",
            text: "皇宫",
            size: 6,
            range_size: 0,
            color: "#000000",
            background_color: "#FFF68F",
            border_color: "#000000",
        },
        {
            name: "衙门",
            text: "衙门",
            size: 3,
            range_size: 7,
            color: "#000000",
            background_color: "#D1EEEE",
            border_color: "#000000",
        },
        {
            name: "贸易站",
            text: "贸易站",
            size: 3,
            range_size: 0,
            color: "#000000",
            background_color: "#98F5FF",
            border_color: "#000000",
        },
        {
            name: "税务局",
            text: "税",
            size: 1,
            range_size: 4,
            color: "#000000",
            background_color: "#ff3838",
            border_color: "#000000",
        },
        {
            name: "大磨坊",
            text: "大磨坊",
            size: 2,
            range_size: 4,
            color: "#000000",
            background_color: "#C0FF3E",
            border_color: "#000000",
        },
        {
            name: "浇灌渠",
            text: "浇灌渠",
            size: 2,
            range_size: 4,
            color: "#000000",
            background_color: "#C0FF3E",
            border_color: "#000000",
        },
    ],
    文化: [
        {
            name: "武馆",
            text: "武馆",
            size: 3,
            range_size: 8,
            color: "#000000",
            background_color: "#EEE8AA",
            border_color: "#000000",
        },
        {
            name: "擂台",
            text: "擂台",
            size: 2,
            range_size: 9,
            color: "#000000",
            background_color: "#EEDFCC",
            border_color: "#000000",
        },
        {
            name: "书院",
            text: "书院",
            size: 4,
            range_size: 9,
            color: "#000000",
            background_color: "#EED5B7",
            border_color: "#000000",
        },
        {
            name: "戏台",
            text: "戏台",
            size: 3,
            range_size: 8,
            color: "#000000",
            background_color: "#EEC900",
            border_color: "#000000",
        },
        {
            name: "观象台",
            text: "观象台",
            size: 4,
            range_size: 10,
            color: "#000000",
            background_color: "#EEAEEE",
            border_color: "#000000",
        },
    ],
    宗教: [
        {
            name: "土地庙",
            text: "庙",
            size: 1,
            range_size: 5,
            color: "#000000",
            background_color: "#CDBA96",
            border_color: "#000000",
        },
        {
            name: "佛寺",
            text: "佛寺",
            size: 3,
            range_size: 8,
            color: "#000000",
            background_color: "#CD9B9B",
            border_color: "#000000",
        },
        {
            name: "道观",
            text: "道观",
            size: 3,
            range_size: 8,
            color: "#000000",
            background_color: "#CD8162",
            border_color: "#000000",
        },
        {
            name: "佛塔",
            text: "佛塔",
            size: 2,
            range_size: 9,
            color: "#000000",
            background_color: "#CD5C5C",
            border_color: "#000000",
        },
    ],
    军事: [
        {
            name: "步兵兵营",
            text: "步兵",
            size: 2,
            range_size: 0,
            color: "#000000",
            background_color: "#CD5B45",
            border_color: "#000000",
        },
        {
            name: "弩兵兵营",
            text: "弩兵",
            size: 2,
            range_size: 0,
            color: "#000000",
            background_color: "#CD5555",
            border_color: "#000000",
        },
        {
            name: "骑兵兵营",
            text: "骑兵兵营",
            size: 3,
            range_size: 0,
            color: "#000000",
            background_color: "#CD4F39",
            border_color: "#000000",
        },
        {
            name: "祭坛",
            text: "祭坛",
            size: 3,
            range_size: 0,
            color: "#000000",
            background_color: "#CD3700",
            border_color: "#000000",
        },
        {
            name: "武器铺",
            text: "武器铺",
            size: 2,
            range_size: 0,
            color: "#000000",
            background_color: "#CD3333",
            border_color: "#000000",
        },
        {
            name: "马厩",
            text: "马厩",
            size: 2,
            range_size: 0,
            color: "#000000",
            background_color: "#CD3278",
            border_color: "#000000",
        },
    ],
    美化: [
        {
            name: "树",
            text: "树",
            size: 1,
            range_size: 0,
            color: "#000000",
            background_color: "#00FF7F",
            border_color: "#000000",
        },
        {
            name: "城墙",
            text: "墙",
            size: 1,
            range_size: 0,
            color: "#FFFFFF",
            background_color: "#696A6B",
            border_color: "#000000",
        },
        {
            name: "城门",
            text: "门",
            size: 1,
            range_size: 0,
            color: "#000000",
            background_color: "#C06D2F",
            border_color: "#000000",
        },
    ],
    奇迹: [
        {
            name: "大雁塔",
            text: "大雁塔",
            size: 5,
            range_size: 0,
            color: "#000000",
            background_color: "#FFF68F",
            border_color: "#000000",
        },
        {
            name: "乐山大佛",
            text: "乐山大佛",
            size: 9,
            range_size: 0,
            color: "#000000",
            background_color: "#FFF68F",
            border_color: "#000000",
        },
        {
            name: "天坛",
            text: "天坛",
            size: 8,
            range_size: 0,
            color: "#000000",
            background_color: "#FFF68F",
            border_color: "#000000",
        },
        {
            name: "布达拉宫",
            text: "布达拉宫",
            size: 16,
            range_size: 0,
            color: "#000000",
            background_color: "#FFF68F",
            border_color: "#000000",
        },
    ],
    通用: [
        {
            name: "2x2建筑",
            text: "2x2",
            size: 2,
            range_size: 0,
            color: "#000000",
            background_color: "#87CEFF",
            border_color: "#000000",
        },
        {
            name: "3x3建筑",
            text: "3x3",
            size: 3,
            range_size: 0,
            color: "#000000",
            background_color: "#fd79a8",
            border_color: "#000000",
        },
        {
            name: "4x4建筑",
            text: "4x4",
            size: 4,
            range_size: 0,
            color: "#000000",
            background_color: "#E6E6FA",
            border_color: "#000000",
        },
        {
            name: "5x5建筑",
            text: "5x5",
            size: 5,
            range_size: 0,
            color: "#000000",
            background_color: "#AEEEEE",
            border_color: "#000000",
        },
    ],
};
