const BuildingChina = {
    防: ["值", "捕", "永和"],
    防护: ["值更房", "捕快房", "永和堂"],
    普通住宅需求: {
        商业: ["粮店", "蔬菜摊", "水果摊", "肉铺", "鱼摊", "瓷器店", "铜器店", "酒馆"],
        市政: ["水井", "衙门"],
        文化: ["武馆", "书院"],
        宗教: ["土地庙"],
    },
    高级住宅需求: {
        商业: ["粮店", "蔬菜摊", "水果摊", "肉铺", "鱼摊", "瓷器店", "铜器店", "酒馆", "纸墨轩", "茶馆", "丝绸店"],
        市政: ["水井", "衙门"],
        文化: ["武馆", "擂台", "书院", "戏台", "观象台"],
        宗教: ["佛寺", "道观", "佛塔"],
    },
    住宅: [
        {
            name: "普通住宅",
            text: "宅",
            size: 1,
            range_size: 0,
            color: BuildingColor.Black,
            background_color: BuildingColor["住宅"][0],
            border_color: BuildingColor.Black,
        },
        {
            name: "高级住宅",
            text: "高级住宅",
            size: 3,
            range_size: 0,
            color: BuildingColor.Black,
            background_color: BuildingColor["住宅"][1],
            border_color: BuildingColor.Black,
        },
    ],
    农业: [
        {
            name: "水稻田",
            text: "水稻田",
            size: 5,
            range_size: 0,
            color: BuildingColor.Black,
            background_color: BuildingColor["农业"][0],
            border_color: BuildingColor.Black,
        },
        {
            name: "白菜地",
            text: "白菜地",
            size: 3,
            range_size: 0,
            color: BuildingColor.Black,
            background_color: BuildingColor["农业"][1],
            border_color: BuildingColor.Black,
        },
        {
            name: "梨园",
            text: "梨园",
            size: 3,
            range_size: 0,
            color: BuildingColor.Black,
            background_color: BuildingColor["农业"][2],
            border_color: BuildingColor.Black,
        },
        {
            name: "猎户小屋",
            text: "猎户",
            size: 2,
            range_size: 0,
            color: BuildingColor.Black,
            background_color: BuildingColor["农业"][3],
            border_color: BuildingColor.Black,
        },
        {
            name: "高粱地",
            text: "高粱地",
            size: 3,
            range_size: 0,
            color: BuildingColor.Black,
            background_color: BuildingColor["农业"][4],
            border_color: BuildingColor.Black,
        },
        {
            name: "茶树小屋",
            text: "茶树小屋",
            size: 4,
            range_size: 0,
            color: BuildingColor.Black,
            background_color: BuildingColor["农业"][5],
            border_color: BuildingColor.Black,
        },
        {
            name: "养蚕小屋",
            text: "养蚕小屋",
            size: 3,
            range_size: 0,
            color: BuildingColor.Black,
            background_color: BuildingColor["农业"][6],
            border_color: BuildingColor.Black,
        },
    ],
    工业: [
        {
            name: "瓦窑",
            text: "瓦窑",
            size: 2,
            range_size: 0,
            color: BuildingColor.Black,
            background_color: BuildingColor["工业"][0],
            border_color: BuildingColor.Black,
        },
        {
            name: "砖窑",
            text: "砖窑",
            size: 2,
            range_size: 0,
            color: BuildingColor.Black,
            background_color: BuildingColor["工业"][1],
            border_color: BuildingColor.Black,
        },
        {
            name: "炼铜厂",
            text: "炼铜厂",
            size: 2,
            range_size: 0,
            color: BuildingColor.Black,
            background_color: BuildingColor["工业"][2],
            border_color: BuildingColor.Black,
        },
        {
            name: "瓷器场",
            text: "瓷器场",
            size: 2,
            range_size: 0,
            color: BuildingColor.Black,
            background_color: BuildingColor["工业"][3],
            border_color: BuildingColor.Black,
        },
        {
            name: "铜器厂",
            text: "铜器厂",
            size: 2,
            range_size: 0,
            color: BuildingColor.Black,
            background_color: BuildingColor["工业"][4],
            border_color: BuildingColor.Black,
        },
        {
            name: "酒厂",
            text: "酒厂",
            size: 3,
            range_size: 0,
            color: BuildingColor.Black,
            background_color: BuildingColor["工业"][5],
            border_color: BuildingColor.Black,
        },
        {
            name: "造纸厂",
            text: "造纸厂",
            size: 3,
            range_size: 0,
            color: BuildingColor.Black,
            background_color: BuildingColor["工业"][6],
            border_color: BuildingColor.Black,
        },
        {
            name: "染坊",
            text: "染坊",
            size: 3,
            range_size: 0,
            color: BuildingColor.Black,
            background_color: BuildingColor["工业"][7],
            border_color: BuildingColor.Black,
        },
    ],
    商业: [
        {
            name: "粮店",
            text: "粮",
            size: 1,
            range_size: 5,
            color: BuildingColor.Black,
            background_color: BuildingColor["商业"][0],
            border_color: BuildingColor.Black,
        },
        {
            name: "蔬菜摊",
            text: "菜",
            size: 1,
            range_size: 5,
            color: BuildingColor.Black,
            background_color: BuildingColor["商业"][1],
            border_color: BuildingColor.Black,
        },
        {
            name: "水果摊",
            text: "果",
            size: 1,
            range_size: 5,
            color: BuildingColor.Black,
            background_color: BuildingColor["商业"][2],
            border_color: BuildingColor.Black,
        },
        {
            name: "肉铺",
            text: "肉",
            size: 1,
            range_size: 5,
            color: BuildingColor.Black,
            background_color: BuildingColor["商业"][3],
            border_color: BuildingColor.Black,
        },
        {
            name: "鱼摊",
            text: "鱼",
            size: 1,
            range_size: 5,
            color: BuildingColor.Black,
            background_color: BuildingColor["商业"][4],
            border_color: BuildingColor.Black,
        },
        {
            name: "瓷器店",
            text: "瓷",
            size: 1,
            range_size: 5,
            color: BuildingColor.Black,
            background_color: BuildingColor["商业"][5],
            border_color: BuildingColor.Black,
        },
        {
            name: "铜器店",
            text: "铜",
            size: 1,
            range_size: 5,
            color: BuildingColor.Black,
            background_color: BuildingColor["商业"][6],
            border_color: BuildingColor.Black,
        },
        {
            name: "酒馆",
            text: "酒",
            size: 1,
            range_size: 5,
            color: BuildingColor.Black,
            background_color: BuildingColor["商业"][7],
            border_color: BuildingColor.Black,
        },
        {
            name: "纸墨轩",
            text: "纸",
            size: 1,
            range_size: 5,
            color: BuildingColor.Black,
            background_color: BuildingColor["商业"][8],
            border_color: BuildingColor.Black,
        },
        {
            name: "茶馆",
            text: "茶",
            size: 1,
            range_size: 5,
            color: BuildingColor.Black,
            background_color: BuildingColor["商业"][9],
            border_color: BuildingColor.Black,
        },
        {
            name: "丝绸店",
            text: "绸",
            size: 1,
            range_size: 5,
            color: BuildingColor.Black,
            background_color: BuildingColor["商业"][10],
            border_color: BuildingColor.Black,
        },
    ],
    市政: [
        {
            name: "水井",
            text: "水",
            size: 1,
            range_size: 4,
            color: BuildingColor.Black,
            background_color: BuildingColor["市政"]["水"],
            border_color: BuildingColor.Black,
        },
        {
            name: "值更房",
            text: "值",
            size: 1,
            range_size: 6,
            color: BuildingColor.Black,
            background_color: BuildingColor["市政"]["防"],
            border_color: BuildingColor.Black,
        },
        {
            name: "捕快房",
            text: "捕",
            size: 1,
            range_size: 6,
            color: BuildingColor.Black,
            background_color: BuildingColor["市政"]["防"],
            border_color: BuildingColor.Black,
        },
        {
            name: "永和堂",
            text: "永和",
            size: 2,
            range_size: 7,
            color: BuildingColor.Black,
            background_color: BuildingColor["市政"]["防"],
            border_color: BuildingColor.Black,
        },
        {
            name: "粮仓",
            text: "粮仓",
            size: 2,
            range_size: 0,
            color: BuildingColor.Black,
            background_color: BuildingColor["市政"]["粮"],
            border_color: BuildingColor.Black,
        },
        {
            name: "货栈",
            text: "货栈",
            size: 4,
            range_size: 0,
            color: BuildingColor.Black,
            background_color: BuildingColor["市政"]["货"],
            border_color: BuildingColor.Black,
        },
        {
            name: "皇宫",
            text: "皇宫",
            size: 6,
            range_size: 0,
            color: BuildingColor.Black,
            background_color: BuildingColor["市政"]["殿"],
            border_color: BuildingColor.Black,
        },
        {
            name: "衙门",
            text: "衙门",
            size: 3,
            range_size: 7,
            color: BuildingColor.Black,
            background_color: BuildingColor["市政"]["职"],
            border_color: BuildingColor.Black,
        },
        {
            name: "贸易站",
            text: "贸易站",
            size: 3,
            range_size: 0,
            color: BuildingColor.Black,
            background_color: BuildingColor["市政"]["贸"],
            border_color: BuildingColor.Black,
        },
        {
            name: "税务局",
            text: "税",
            size: 1,
            range_size: 4,
            color: BuildingColor.Black,
            background_color: BuildingColor["市政"]["税"],
            border_color: BuildingColor.Black,
        },
        {
            name: "大磨坊",
            text: "大磨坊",
            size: 2,
            range_size: 4,
            color: BuildingColor.Black,
            background_color: BuildingColor["市政"]["磨"],
            border_color: BuildingColor.Black,
        },
        {
            name: "浇灌渠",
            text: "浇灌渠",
            size: 2,
            range_size: 4,
            color: BuildingColor.Black,
            background_color: BuildingColor["市政"]["浇"],
            border_color: BuildingColor.Black,
        },
    ],
    文化: [
        {
            name: "武馆",
            text: "武馆",
            size: 3,
            range_size: 8,
            color: BuildingColor.Black,
            background_color: BuildingColor["文化"][0],
            border_color: BuildingColor.Black,
        },
        {
            name: "擂台",
            text: "擂台",
            size: 2,
            range_size: 9,
            color: BuildingColor.Black,
            background_color: BuildingColor["文化"][1],
            border_color: BuildingColor.Black,
        },
        {
            name: "书院",
            text: "书院",
            size: 4,
            range_size: 9,
            color: BuildingColor.Black,
            background_color: BuildingColor["文化"][2],
            border_color: BuildingColor.Black,
        },
        {
            name: "戏台",
            text: "戏台",
            size: 3,
            range_size: 8,
            color: BuildingColor.Black,
            background_color: BuildingColor["文化"][3],
            border_color: BuildingColor.Black,
        },
        {
            name: "观象台",
            text: "观象台",
            size: 4,
            range_size: 10,
            color: BuildingColor.Black,
            background_color: BuildingColor["文化"][4],
            border_color: BuildingColor.Black,
        },
    ],
    宗教: [
        {
            name: "土地庙",
            text: "庙",
            size: 1,
            range_size: 5,
            color: BuildingColor.White,
            background_color: BuildingColor["宗教"][0],
            border_color: BuildingColor.Black,
        },
        {
            name: "佛寺",
            text: "佛寺",
            size: 3,
            range_size: 8,
            color: BuildingColor.White,
            background_color: BuildingColor["宗教"][1],
            border_color: BuildingColor.Black,
        },
        {
            name: "道观",
            text: "道观",
            size: 3,
            range_size: 8,
            color: BuildingColor.White,
            background_color: BuildingColor["宗教"][2],
            border_color: BuildingColor.Black,
        },
        {
            name: "佛塔",
            text: "佛塔",
            size: 2,
            range_size: 9,
            color: BuildingColor.White,
            background_color: BuildingColor["宗教"][3],
            border_color: BuildingColor.Black,
        },
    ],
    军事: [
        {
            name: "步兵兵营",
            text: "步兵",
            size: 2,
            range_size: 0,
            color: BuildingColor.White,
            background_color: BuildingColor["军事"][0],
            border_color: BuildingColor.Black,
        },
        {
            name: "弩兵兵营",
            text: "弩兵",
            size: 2,
            range_size: 0,
            color: BuildingColor.White,
            background_color: BuildingColor["军事"][1],
            border_color: BuildingColor.Black,
        },
        {
            name: "骑兵兵营",
            text: "骑兵兵营",
            size: 3,
            range_size: 0,
            color: BuildingColor.White,
            background_color: BuildingColor["军事"][2],
            border_color: BuildingColor.Black,
        },
        {
            name: "祭坛",
            text: "祭坛",
            size: 3,
            range_size: 0,
            color: BuildingColor.White,
            background_color: BuildingColor["军事"][3],
            border_color: BuildingColor.Black,
        },
        {
            name: "武器铺",
            text: "武器铺",
            size: 2,
            range_size: 0,
            color: BuildingColor.White,
            background_color: BuildingColor["军事"][4],
            border_color: BuildingColor.Black,
        },
        {
            name: "马厩",
            text: "马厩",
            size: 2,
            range_size: 0,
            color: BuildingColor.White,
            background_color: BuildingColor["军事"][5],
            border_color: BuildingColor.Black,
        },
    ],
    美化: [
        {
            name: "树",
            text: "树",
            size: 1,
            range_size: 0,
            color: BuildingColor.Black,
            background_color: BuildingColor["美化"]["树"],
            border_color: BuildingColor.Black,
        },
        {
            name: "城墙",
            text: "墙",
            size: 1,
            range_size: 0,
            color: BuildingColor.White,
            background_color: BuildingColor["美化"]["墙"],
            border_color: BuildingColor.Black,
        },
        {
            name: "城门",
            text: "门",
            size: 1,
            range_size: 0,
            color: BuildingColor.White,
            background_color: BuildingColor["美化"]["门"],
            border_color: BuildingColor.Black,
        },
    ],
    奇迹: [
        {
            name: "大雁塔",
            text: "大雁塔",
            size: 5,
            range_size: 0,
            color: BuildingColor.White,
            background_color: BuildingColor["奇迹"][0],
            border_color: BuildingColor.Black,
        },
        {
            name: "乐山大佛",
            text: "乐山大佛",
            size: 9,
            range_size: 0,
            color: BuildingColor.White,
            background_color: BuildingColor["奇迹"][1],
            border_color: BuildingColor.Black,
        },
        {
            name: "天坛",
            text: "天坛",
            size: 8,
            range_size: 0,
            color: BuildingColor.White,
            background_color: BuildingColor["奇迹"][2],
            border_color: BuildingColor.Black,
        },
        {
            name: "布达拉宫",
            text: "布达拉宫",
            size: 16,
            range_size: 0,
            color: BuildingColor.White,
            background_color: BuildingColor["奇迹"][3],
            border_color: BuildingColor.Black,
        },
    ],
    通用: [
        {
            name: "2x2建筑",
            text: "2x2",
            size: 2,
            range_size: 0,
            color: BuildingColor.Black,
            background_color: BuildingColor["通用"][0],
            border_color: BuildingColor.Black,
        },
        {
            name: "3x3建筑",
            text: "3x3",
            size: 3,
            range_size: 0,
            color: BuildingColor.Black,
            background_color: BuildingColor["通用"][1],
            border_color: BuildingColor.Black,
        },
        {
            name: "4x4建筑",
            text: "4x4",
            size: 4,
            range_size: 0,
            color: BuildingColor.Black,
            background_color: BuildingColor["通用"][2],
            border_color: BuildingColor.Black,
        },
        {
            name: "5x5建筑",
            text: "5x5",
            size: 5,
            range_size: 0,
            color: BuildingColor.Black,
            background_color: BuildingColor["通用"][3],
            border_color: BuildingColor.Black,
        },
    ],
};
