const BuildingPersian = {
    防: ["消", "维", "治", "医疗"],
    防护: ["消防局", "维修站", "治安厅", "医疗站"],
    普通住宅需求: {
        商业: ["粮食货摊", "蔬菜货摊", "水果货摊", "生肉货摊", "鱼虾货摊", "瓷器货摊", "香料货摊", "地毯货摊"],
        市政: ["饮水台", "办公厅"],
        文化: ["斗兽场"],
        宗教: ["礼拜堂", "小清真寺"],
    },
    高级住宅需求: {
        商业: [
            "粮食货摊",
            "蔬菜货摊",
            "水果货摊",
            "生肉货摊",
            "鱼虾货摊",
            "瓷器货摊",
            "香料货摊",
            "地毯货摊",
            "糖品货摊",
            "烟草货摊",
            "芝麻油货摊",
            "葡萄酒货摊",
        ],
        市政: ["饮水台", "办公厅"],
        文化: ["浴池", "斗兽场", "大学", "观星台"],
        宗教: ["小清真寺", "大清真寺"],
    },
    住宅: [
        {
            name: "普通住宅",
            text: "宅",
            size: 1,
            range_size: 0,
            color: BuildingColor.Black,
            background_color: BuildingColor["住宅"][0],
            border_color: BuildingColor.Black,
        },
        {
            name: "高级住宅",
            text: "别墅",
            size: 2,
            range_size: 0,
            color: BuildingColor.Black,
            background_color: BuildingColor["住宅"][1],
            border_color: BuildingColor.Black,
        },
    ],
    农业: [
        {
            name: "麦田",
            text: "麦田",
            size: 3,
            range_size: 0,
            color: BuildingColor.Black,
            background_color: BuildingColor["农业"][0],
            border_color: BuildingColor.Black,
        },
        {
            name: "菠菜田",
            text: "菠菜田",
            size: 3,
            range_size: 0,
            color: BuildingColor.Black,
            background_color: BuildingColor["农业"][1],
            border_color: BuildingColor.Black,
        },
        {
            name: "椰枣园",
            text: "椰枣园",
            size: 3,
            range_size: 0,
            color: BuildingColor.Black,
            background_color: BuildingColor["农业"][2],
            border_color: BuildingColor.Black,
        },
        {
            name: "猎户小屋",
            text: "猎户",
            size: 2,
            range_size: 0,
            color: BuildingColor.Black,
            background_color: BuildingColor["农业"][3],
            border_color: BuildingColor.Black,
        },
        {
            name: "绵阳牧场",
            text: "绵阳牧场",
            size: 3,
            range_size: 0,
            color: BuildingColor.Black,
            background_color: BuildingColor["农业"][4],
            border_color: BuildingColor.Black,
        },
        {
            name: "甜菜田",
            text: "甜菜田",
            size: 3,
            range_size: 0,
            color: BuildingColor.Black,
            background_color: BuildingColor["农业"][5],
            border_color: BuildingColor.Black,
        },
        {
            name: "烟草田",
            text: "烟草田",
            size: 3,
            range_size: 0,
            color: BuildingColor.Black,
            background_color: BuildingColor["农业"][6],
            border_color: BuildingColor.Black,
        },
        {
            name: "芝麻田",
            text: "芝麻田",
            size: 3,
            range_size: 0,
            color: BuildingColor.Black,
            background_color: BuildingColor["农业"][7],
            border_color: BuildingColor.Black,
        },
        {
            name: "葡萄园",
            text: "葡萄园",
            size: 3,
            range_size: 0,
            color: BuildingColor.Black,
            background_color: BuildingColor["农业"][8],
            border_color: BuildingColor.Black,
        },
    ],
    工业: [
        {
            name: "砖窑",
            text: "砖窑",
            size: 2,
            range_size: 0,
            color: BuildingColor.Black,
            background_color: BuildingColor["工业"][0],
            border_color: BuildingColor.Black,
        },
        {
            name: "炼铜场",
            text: "炼铜场",
            size: 2,
            range_size: 0,
            color: BuildingColor.Black,
            background_color: BuildingColor["工业"][1],
            border_color: BuildingColor.Black,
        },
        {
            name: "陶瓷场",
            text: "陶瓷场",
            size: 2,
            range_size: 0,
            color: BuildingColor.Black,
            background_color: BuildingColor["工业"][2],
            border_color: BuildingColor.Black,
        },
        {
            name: "香料作坊",
            text: "香料作坊",
            size: 2,
            range_size: 0,
            color: BuildingColor.Black,
            background_color: BuildingColor["工业"][3],
            border_color: BuildingColor.Black,
        },
        {
            name: "地毯作坊",
            text: "地毯作坊",
            size: 2,
            range_size: 0,
            color: BuildingColor.Black,
            background_color: BuildingColor["工业"][4],
            border_color: BuildingColor.Black,
        },
        {
            name: "制糖厂",
            text: "制糖厂",
            size: 2,
            range_size: 0,
            color: BuildingColor.Black,
            background_color: BuildingColor["工业"][5],
            border_color: BuildingColor.Black,
        },
        {
            name: "油坊",
            text: "油坊",
            size: 2,
            range_size: 0,
            color: BuildingColor.Black,
            background_color: BuildingColor["工业"][6],
            border_color: BuildingColor.Black,
        },
        {
            name: "酒坊",
            text: "酒坊",
            size: 2,
            range_size: 0,
            color: BuildingColor.Black,
            background_color: BuildingColor["工业"][7],
            border_color: BuildingColor.Black,
        },
    ],
    商业: [
        {
            name: "粮食货摊",
            text: "粮",
            size: 1,
            range_size: 5,
            color: BuildingColor.Black,
            background_color: BuildingColor["商业"][0],
            border_color: BuildingColor.Black,
        },
        {
            name: "蔬菜货摊",
            text: "菜",
            size: 1,
            range_size: 5,
            color: BuildingColor.Black,
            background_color: BuildingColor["商业"][1],
            border_color: BuildingColor.Black,
        },
        {
            name: "水果货摊",
            text: "果",
            size: 1,
            range_size: 5,
            color: BuildingColor.Black,
            background_color: BuildingColor["商业"][2],
            border_color: BuildingColor.Black,
        },
        {
            name: "生肉货摊",
            text: "肉",
            size: 1,
            range_size: 5,
            color: BuildingColor.Black,
            background_color: BuildingColor["商业"][3],
            border_color: BuildingColor.Black,
        },
        {
            name: "鱼虾货摊",
            text: "鱼",
            size: 1,
            range_size: 5,
            color: BuildingColor.Black,
            background_color: BuildingColor["商业"][4],
            border_color: BuildingColor.Black,
        },
        {
            name: "瓷器货摊",
            text: "瓷",
            size: 1,
            range_size: 5,
            color: BuildingColor.Black,
            background_color: BuildingColor["商业"][5],
            border_color: BuildingColor.Black,
        },
        {
            name: "香料货摊",
            text: "香",
            size: 1,
            range_size: 5,
            color: BuildingColor.Black,
            background_color: BuildingColor["商业"][6],
            border_color: BuildingColor.Black,
        },
        {
            name: "地毯货摊",
            text: "毯",
            size: 1,
            range_size: 5,
            color: BuildingColor.Black,
            background_color: BuildingColor["商业"][7],
            border_color: BuildingColor.Black,
        },
        {
            name: "糖品货摊",
            text: "糖",
            size: 1,
            range_size: 5,
            color: BuildingColor.Black,
            background_color: BuildingColor["商业"][8],
            border_color: BuildingColor.Black,
        },
        {
            name: "烟草货摊",
            text: "烟",
            size: 1,
            range_size: 5,
            color: BuildingColor.Black,
            background_color: BuildingColor["商业"][9],
            border_color: BuildingColor.Black,
        },
        {
            name: "芝麻油货摊",
            text: "油",
            size: 1,
            range_size: 5,
            color: BuildingColor.Black,
            background_color: BuildingColor["商业"][10],
            border_color: BuildingColor.Black,
        },
        {
            name: "葡萄酒货摊",
            text: "酒",
            size: 1,
            range_size: 5,
            color: BuildingColor.Black,
            background_color: BuildingColor["商业"][11],
            border_color: BuildingColor.Black,
        },
    ],
    市政: [
        {
            name: "饮水台",
            text: "水",
            size: 1,
            range_size: 4,
            color: BuildingColor.Black,
            background_color: BuildingColor["市政"]["水"],
            border_color: BuildingColor.Black,
        },
        {
            name: "消防局",
            text: "消",
            size: 1,
            range_size: 6,
            color: BuildingColor.Black,
            background_color: BuildingColor["市政"]["防"],
            border_color: BuildingColor.Black,
        },
        {
            name: "维修站",
            text: "维",
            size: 1,
            range_size: 6,
            color: BuildingColor.Black,
            background_color: BuildingColor["市政"]["防"],
            border_color: BuildingColor.Black,
        },
        {
            name: "治安厅",
            text: "治",
            size: 1,
            range_size: 6,
            color: BuildingColor.Black,
            background_color: BuildingColor["市政"]["防"],
            border_color: BuildingColor.Black,
        },
        {
            name: "医疗站",
            text: "医疗",
            size: 2,
            range_size: 7,
            color: BuildingColor.Black,
            background_color: BuildingColor["市政"]["防"],
            border_color: BuildingColor.Black,
        },
        {
            name: "粮仓",
            text: "粮仓",
            size: 3,
            range_size: 0,
            color: BuildingColor.Black,
            background_color: BuildingColor["市政"]["粮"],
            border_color: BuildingColor.Black,
        },
        {
            name: "货栈",
            text: "货栈",
            size: 4,
            range_size: 0,
            color: BuildingColor.Black,
            background_color: BuildingColor["市政"]["货"],
            border_color: BuildingColor.Black,
        },
        {
            name: "宫殿",
            text: "宫殿",
            size: 4,
            range_size: 0,
            color: BuildingColor.Black,
            background_color: BuildingColor["市政"]["殿"],
            border_color: BuildingColor.Black,
        },
        {
            name: "办公厅",
            text: "办公厅",
            size: 2,
            range_size: 6,
            color: BuildingColor.Black,
            background_color: BuildingColor["市政"]["职"],
            border_color: BuildingColor.Black,
        },
        {
            name: "贸易站",
            text: "贸易站",
            size: 2,
            range_size: 0,
            color: BuildingColor.Black,
            background_color: BuildingColor["市政"]["贸"],
            border_color: BuildingColor.Black,
        },
        {
            name: "税务局",
            text: "税",
            size: 1,
            range_size: 4,
            color: BuildingColor.Black,
            background_color: BuildingColor["市政"]["税"],
            border_color: BuildingColor.Black,
        },
        {
            name: "磨坊",
            text: "磨坊",
            size: 1,
            range_size: 4,
            color: BuildingColor.Black,
            background_color: BuildingColor["市政"]["磨"],
            border_color: BuildingColor.Black,
        },
        {
            name: "水车房",
            text: "水车房",
            size: 2,
            range_size: 4,
            color: BuildingColor.Black,
            background_color: BuildingColor["市政"]["浇"],
            border_color: BuildingColor.Black,
        },
        {
            name: "驿站",
            text: "驿站",
            size: 2,
            range_size: 0,
            color: BuildingColor.Black,
            background_color: BuildingColor["市政"]["驿"],
            border_color: BuildingColor.Black,
        },
    ],
    文化: [
        {
            name: "浴池",
            text: "浴池",
            size: 2,
            range_size: 8,
            color: BuildingColor.Black,
            background_color: BuildingColor["文化"][0],
            border_color: BuildingColor.Black,
        },
        {
            name: "斗兽场",
            text: "斗兽场",
            size: 4,
            range_size: 8,
            color: BuildingColor.Black,
            background_color: BuildingColor["文化"][1],
            border_color: BuildingColor.Black,
        },
        {
            name: "大学",
            text: "大学",
            size: 3,
            range_size: 8,
            color: BuildingColor.Black,
            background_color: BuildingColor["文化"][2],
            border_color: BuildingColor.Black,
        },
        {
            name: "观星台",
            text: "观星台",
            size: 3,
            range_size: 8,
            color: BuildingColor.Black,
            background_color: BuildingColor["文化"][3],
            border_color: BuildingColor.Black,
        },
    ],
    宗教: [
        {
            name: "礼拜堂",
            text: "礼",
            size: 1,
            range_size: 6,
            color: BuildingColor.White,
            background_color: BuildingColor["宗教"][0],
            border_color: BuildingColor.Black,
        },
        {
            name: "小清真寺",
            text: "小清真",
            size: 2,
            range_size: 8,
            color: BuildingColor.White,
            background_color: BuildingColor["宗教"][1],
            border_color: BuildingColor.Black,
        },
        {
            name: "大清真寺",
            text: "大清真寺",
            size: 4,
            range_size: 10,
            color: BuildingColor.White,
            background_color: BuildingColor["宗教"][2],
            border_color: BuildingColor.Black,
        },
    ],
    军事: [
        {
            name: "步兵兵营",
            text: "步兵",
            size: 2,
            range_size: 0,
            color: BuildingColor.White,
            background_color: BuildingColor["军事"][0],
            border_color: BuildingColor.Black,
        },
        {
            name: "射手兵营",
            text: "射手",
            size: 2,
            range_size: 0,
            color: BuildingColor.White,
            background_color: BuildingColor["军事"][1],
            border_color: BuildingColor.Black,
        },
        {
            name: "骑兵兵营",
            text: "骑兵",
            size: 2,
            range_size: 0,
            color: BuildingColor.White,
            background_color: BuildingColor["军事"][2],
            border_color: BuildingColor.Black,
        },
        {
            name: "军事学院",
            text: "军事",
            size: 3,
            range_size: 0,
            color: BuildingColor.White,
            background_color: BuildingColor["军事"][3],
            border_color: BuildingColor.Black,
        },
        {
            name: "武器铺",
            text: "武器铺",
            size: 2,
            range_size: 0,
            color: BuildingColor.White,
            background_color: BuildingColor["军事"][4],
            border_color: BuildingColor.Black,
        },
        {
            name: "马厩",
            text: "马厩",
            size: 2,
            range_size: 0,
            color: BuildingColor.White,
            background_color: BuildingColor["军事"][5],
            border_color: BuildingColor.Black,
        },
        {
            name: "象棚",
            text: "象棚",
            size: 3,
            range_size: 0,
            color: BuildingColor.White,
            background_color: BuildingColor["军事"][6],
            border_color: BuildingColor.Black,
        },
    ],
    美化: [
        {
            name: "树",
            text: "树",
            size: 1,
            range_size: 0,
            color: BuildingColor.Black,
            background_color: BuildingColor["美化"]["树"],
            border_color: BuildingColor.Black,
        },
    ],
    奇迹: [
        {
            name: "通天塔",
            text: "通天塔",
            size: 6,
            range_size: 0,
            color: BuildingColor.White,
            background_color: BuildingColor["奇迹"][0],
            border_color: BuildingColor.Black,
        },
        {
            name: "空中花园",
            text: "空中花园",
            size: 10,
            range_size: 0,
            color: BuildingColor.White,
            background_color: BuildingColor["奇迹"][1],
            border_color: BuildingColor.Black,
        },
    ],
    通用: [
        {
            name: "2x2建筑",
            text: "2x2",
            size: 2,
            range_size: 0,
            color: BuildingColor.Black,
            background_color: BuildingColor["通用"][0],
            border_color: BuildingColor.Black,
        },
        {
            name: "3x3建筑",
            text: "3x3",
            size: 3,
            range_size: 0,
            color: BuildingColor.Black,
            background_color: BuildingColor["通用"][1],
            border_color: BuildingColor.Black,
        },
        {
            name: "4x4建筑",
            text: "4x4",
            size: 4,
            range_size: 0,
            color: BuildingColor.Black,
            background_color: BuildingColor["通用"][2],
            border_color: BuildingColor.Black,
        },
        {
            name: "5x5建筑",
            text: "5x5",
            size: 5,
            range_size: 0,
            color: BuildingColor.Black,
            background_color: BuildingColor["通用"][3],
            border_color: BuildingColor.Black,
        },
    ],
};
