const BuildingGreece = {
    防: ["消", "维", "瞭", "诊所"],
    防护: ["消防局", "维修所", "瞭望台", "诊所"],
    住宅: [
        {
            name: "普通住宅",
            text: "宅",
            size: 1,
            range_size: 0,
            color: "#000000",
            background_color: "#FFA500",
            border_color: "#000000",
        },
        {
            name: "高级住宅",
            text: "高宅",
            size: 2,
            range_size: 0,
            color: "#000000",
            background_color: "#FFA500",
            border_color: "#000000",
        },
    ],
    农业: [
        {
            name: "麦田",
            text: "麦田",
            size: 2,
            range_size: 0,
            color: "#000000",
            background_color: "#32CD32",
            border_color: "#000000",
        },
        {
            name: "卷心菜小屋",
            text: "卷心菜",
            size: 2,
            range_size: 0,
            color: "#000000",
            background_color: "#32CD32",
            border_color: "#000000",
        },
        {
            name: "桔子小屋",
            text: "桔子",
            size: 2,
            range_size: 0,
            color: "#000000",
            background_color: "#32CD32",
            border_color: "#000000",
        },
        {
            name: "猎人小屋",
            text: "猎人",
            size: 2,
            range_size: 0,
            color: "#000000",
            background_color: "#32CD32",
            border_color: "#000000",
        },
        {
            name: "亚麻小屋",
            text: "亚麻",
            size: 2,
            range_size: 0,
            color: "#000000",
            background_color: "#32CD32",
            border_color: "#000000",
        },
        {
            name: "葡萄园",
            text: "葡萄园",
            size: 2,
            range_size: 0,
            color: "#000000",
            background_color: "#32CD32",
            border_color: "#000000",
        },
        {
            name: "绵羊牧场",
            text: "绵羊牧场",
            size: 3,
            range_size: 0,
            color: "#000000",
            background_color: "#32CD32",
            border_color: "#000000",
        },
        {
            name: "山羊牧场",
            text: "山羊牧场",
            size: 3,
            range_size: 0,
            color: "#000000",
            background_color: "#32CD32",
            border_color: "#000000",
        },
        {
            name: "橄榄园",
            text: "橄榄园",
            size: 2,
            range_size: 0,
            color: "#000000",
            background_color: "#32CD32",
            border_color: "#000000",
        },
    ],
    工业: [
        {
            name: "陶瓦场",
            text: "陶瓦场",
            size: 2,
            range_size: 0,
            color: "#000000",
            background_color: "#40E0D0",
            border_color: "#000000",
        },
        {
            name: "炼铜场",
            text: "炼铜场",
            size: 2,
            range_size: 0,
            color: "#000000",
            background_color: "#40E0D0",
            border_color: "#000000",
        },
        {
            name: "塑料场",
            text: "塑料场",
            size: 2,
            range_size: 0,
            color: "#000000",
            background_color: "#40E0D0",
            border_color: "#000000",
        },
        {
            name: "陶器场",
            text: "陶器场",
            size: 2,
            range_size: 0,
            color: "#000000",
            background_color: "#40E0D0",
            border_color: "#000000",
        },
        {
            name: "纺织厂",
            text: "纺织厂",
            size: 2,
            range_size: 0,
            color: "#000000",
            background_color: "#40E0D0",
            border_color: "#000000",
        },
        {
            name: "酒坊",
            text: "酒坊",
            size: 2,
            range_size: 0,
            color: "#000000",
            background_color: "#40E0D0",
            border_color: "#000000",
        },
        {
            name: "奶酪场",
            text: "奶酪场",
            size: 2,
            range_size: 0,
            color: "#000000",
            background_color: "#40E0D0",
            border_color: "#000000",
        },
        {
            name: "油坊",
            text: "油坊",
            size: 2,
            range_size: 0,
            color: "#000000",
            background_color: "#40E0D0",
            border_color: "#000000",
        },
    ],
    商业: [
        {
            name: "粮食货摊",
            text: "粮",
            size: 1,
            range_size: 5,
            color: "#000000",
            background_color: "#FFEC8B",
            border_color: "#000000",
        },
        {
            name: "蔬菜货摊",
            text: "菜",
            size: 1,
            range_size: 5,
            color: "#000000",
            background_color: "#FFEC8B",
            border_color: "#000000",
        },
        {
            name: "水果货摊",
            text: "果",
            size: 1,
            range_size: 5,
            color: "#000000",
            background_color: "#FFEC8B",
            border_color: "#000000",
        },
        {
            name: "生肉货摊",
            text: "肉",
            size: 1,
            range_size: 5,
            color: "#000000",
            background_color: "#FFEC8B",
            border_color: "#000000",
        },
        {
            name: "鱼虾货摊",
            text: "鱼",
            size: 1,
            range_size: 5,
            color: "#000000",
            background_color: "#FFEC8B",
            border_color: "#000000",
        },
        {
            name: "陶器店",
            text: "陶",
            size: 1,
            range_size: 5,
            color: "#000000",
            background_color: "#FFEC8B",
            border_color: "#000000",
        },
        {
            name: "亚麻布店",
            text: "布",
            size: 1,
            range_size: 5,
            color: "#000000",
            background_color: "#FFEC8B",
            border_color: "#000000",
        },
        {
            name: "酒馆",
            text: "酒",
            size: 1,
            range_size: 5,
            color: "#000000",
            background_color: "#FFEC8B",
            border_color: "#000000",
        },
        {
            name: "羊毛货摊",
            text: "羊",
            size: 1,
            range_size: 5,
            color: "#000000",
            background_color: "#FFEC8B",
            border_color: "#000000",
        },
        {
            name: "奶酪货摊",
            text: "奶",
            size: 1,
            range_size: 5,
            color: "#000000",
            background_color: "#FFEC8B",
            border_color: "#000000",
        },
        {
            name: "橄榄油货摊",
            text: "橄",
            size: 1,
            range_size: 5,
            color: "#000000",
            background_color: "#FFEC8B",
            border_color: "#000000",
        },
    ],
    市政: [
        {
            name: "喷泉",
            text: "水",
            size: 1,
            range_size: 4,
            color: "#000000",
            background_color: "#1E90FF",
            border_color: "#000000",
        },
        {
            name: "消防局",
            text: "消",
            size: 1,
            range_size: 6,
            color: "#000000",
            background_color: "#FF0000",
            border_color: "#000000",
        },
        {
            name: "维修所",
            text: "维",
            size: 1,
            range_size: 6,
            color: "#000000",
            background_color: "#FF0000",
            border_color: "#000000",
        },
        {
            name: "瞭望台",
            text: "瞭",
            size: 1,
            range_size: 7,
            color: "#000000",
            background_color: "#FF0000",
            border_color: "#000000",
        },
        {
            name: "诊所",
            text: "诊所",
            size: 2,
            range_size: 7,
            color: "#000000",
            background_color: "#FF0000",
            border_color: "#000000",
        },
        {
            name: "粮仓",
            text: "粮仓",
            size: 2,
            range_size: 0,
            color: "#000000",
            background_color: "#98F5FF",
            border_color: "#000000",
        },
        {
            name: "货栈",
            text: "货栈",
            size: 3,
            range_size: 0,
            color: "#000000",
            background_color: "#98F5FF",
            border_color: "#000000",
        },
        {
            name: "宫殿",
            text: "宫殿",
            size: 4,
            range_size: 0,
            color: "#000000",
            background_color: "#FFF68F",
            border_color: "#000000",
        },
        {
            name: "议会厅",
            text: "议会厅",
            size: 2,
            range_size: 6,
            color: "#000000",
            background_color: "#D1EEEE",
            border_color: "#000000",
        },
        {
            name: "贸易站",
            text: "贸易站",
            size: 2,
            range_size: 0,
            color: "#000000",
            background_color: "#98F5FF",
            border_color: "#000000",
        },
        {
            name: "税务局",
            text: "税",
            size: 1,
            range_size: 4,
            color: "#000000",
            background_color: "#FF0000",
            border_color: "#000000",
        },
        {
            name: "风力磨坊",
            text: "磨",
            size: 1,
            range_size: 4,
            color: "#000000",
            background_color: "#C0FF3E",
            border_color: "#000000",
        },
        {
            name: "水车",
            text: "水车",
            size: 2,
            range_size: 4,
            color: "#000000",
            background_color: "#C0FF3E",
            border_color: "#000000",
        },
    ],
    文化: [
        {
            name: "剧场",
            text: "剧场",
            size: 2,
            range_size: 6,
            color: "#000000",
            background_color: "#EEE8AA",
            border_color: "#000000",
        },
        {
            name: "露天体育场",
            text: "露天体育场",
            size: 6,
            range_size: 10,
            color: "#000000",
            background_color: "#EEDFCC",
            border_color: "#000000",
        },
        {
            name: "大学",
            text: "大学",
            size: 5,
            range_size: 8,
            color: "#000000",
            background_color: "#EED5B7",
            border_color: "#000000",
        },
        {
            name: "图书馆",
            text: "图书馆",
            size: 5,
            range_size: 8,
            color: "#000000",
            background_color: "#EEC900",
            border_color: "#000000",
        },
    ],
    宗教: [
        {
            name: "小神殿",
            text: "小神殿",
            size: 2,
            range_size: 5,
            color: "#000000",
            background_color: "#CDBA96",
            border_color: "#000000",
        },
        {
            name: "中神殿",
            text: "中神殿",
            size: 3,
            range_size: 7,
            color: "#000000",
            background_color: "#CD9B9B",
            border_color: "#000000",
        },
        {
            name: "大神殿",
            text: "大神殿",
            size: 8,
            range_size: 9,
            color: "#000000",
            background_color: "#CD8162",
            border_color: "#000000",
        },
    ],
    军事: [
        {
            name: "步兵兵营",
            text: "步兵",
            size: 2,
            range_size: 0,
            color: "#000000",
            background_color: "#CD5B45",
            border_color: "#000000",
        },
        {
            name: "射手兵营",
            text: "射手",
            size: 2,
            range_size: 0,
            color: "#000000",
            background_color: "#CD5555",
            border_color: "#000000",
        },
        {
            name: "祭坛",
            text: "祭坛",
            size: 2,
            range_size: 0,
            color: "#000000",
            background_color: "#CD3700",
            border_color: "#000000",
        },
        {
            name: "武器铺",
            text: "武器铺",
            size: 2,
            range_size: 0,
            color: "#000000",
            background_color: "#CD3333",
            border_color: "#000000",
        },
        {
            name: "马厩",
            text: "马厩",
            size: 2,
            range_size: 0,
            color: "#000000",
            background_color: "#CD3278",
            border_color: "#000000",
        },
    ],
    美化: [
        {
            name: "树",
            text: "树",
            size: 1,
            range_size: 0,
            color: "#000000",
            background_color: "#00FF7F",
            border_color: "#000000",
        },
    ],
    奇迹: [
        {
            name: "特洛伊木马",
            text: "特洛伊木马",
            size: 3,
            range_size: 0,
            color: "#000000",
            background_color: "#FFF68F",
            border_color: "#000000",
        },
        {
            name: "宙斯神像",
            text: "宙斯神像",
            size: 4,
            range_size: 0,
            color: "#000000",
            background_color: "#FFF68F",
            border_color: "#000000",
        },
        {
            name: "罗德岛巨像",
            text: "罗德岛巨像",
            size: 3,
            range_size: 0,
            color: "#000000",
            background_color: "#FFF68F",
            border_color: "#000000",
        },
        {
            name: "摩索拉斯基陵墓",
            text: "摩索拉斯基陵墓",
            size: 5,
            range_size: 0,
            color: "#000000",
            background_color: "#FFF68F",
            border_color: "#000000",
        },
    ],
    通用: [
        {
            name: "2x2建筑",
            text: "2x2",
            size: 2,
            range_size: 0,
            color: "#000000",
            background_color: "#87CEFF",
            border_color: "#000000",
        },
        {
            name: "3x3建筑",
            text: "3x3",
            size: 3,
            range_size: 0,
            color: "#000000",
            background_color: "#FF3E96",
            border_color: "#000000",
        },
        {
            name: "4x4建筑",
            text: "4x4",
            size: 4,
            range_size: 0,
            color: "#000000",
            background_color: "#E6E6FA",
            border_color: "#000000",
        },
        {
            name: "5x5建筑",
            text: "5x5",
            size: 5,
            range_size: 0,
            color: "#000000",
            background_color: "#AEEEEE",
            border_color: "#000000",
        },
    ],
};
