const BuildingPersian = {
    防: ["消", "维", "治", "医疗"],
    住宅: [
        {
            name: "普通住宅",
            text: "宅",
            size: 1,
            range_size: 0,
            color: "#000000",
            background_color: "#FFA500",
            border_color: "#000000",
        },
        {
            name: "高级住宅",
            text: "别墅",
            size: 2,
            range_size: 0,
            color: "#000000",
            background_color: "#FFA500",
            border_color: "#000000",
        },
    ],
    农业: [
        {
            name: "麦田",
            text: "麦田",
            size: 3,
            range_size: 0,
            color: "#000000",
            background_color: "#32CD32",
            border_color: "#000000",
        },
        {
            name: "菠菜田",
            text: "菠菜田",
            size: 3,
            range_size: 0,
            color: "#000000",
            background_color: "#32CD32",
            border_color: "#000000",
        },
        {
            name: "椰枣园",
            text: "椰枣园",
            size: 3,
            range_size: 0,
            color: "#000000",
            background_color: "#32CD32",
            border_color: "#000000",
        },
        {
            name: "猎户小屋",
            text: "猎户",
            size: 2,
            range_size: 0,
            color: "#000000",
            background_color: "#32CD32",
            border_color: "#000000",
        },
        {
            name: "绵阳牧场",
            text: "绵阳牧场",
            size: 3,
            range_size: 0,
            color: "#000000",
            background_color: "#32CD32",
            border_color: "#000000",
        },
        {
            name: "甜菜田",
            text: "甜菜田",
            size: 3,
            range_size: 0,
            color: "#000000",
            background_color: "#32CD32",
            border_color: "#000000",
        },
        {
            name: "烟草田",
            text: "烟草田",
            size: 3,
            range_size: 0,
            color: "#000000",
            background_color: "#32CD32",
            border_color: "#000000",
        },
        {
            name: "芝麻田",
            text: "芝麻田",
            size: 3,
            range_size: 0,
            color: "#000000",
            background_color: "#32CD32",
            border_color: "#000000",
        },
        {
            name: "葡萄园",
            text: "葡萄园",
            size: 3,
            range_size: 0,
            color: "#000000",
            background_color: "#32CD32",
            border_color: "#000000",
        },
    ],
    工业: [
        {
            name: "砖窑",
            text: "砖窑",
            size: 2,
            range_size: 0,
            color: "#000000",
            background_color: "#40E0D0",
            border_color: "#000000",
        },
        {
            name: "炼铜场",
            text: "炼铜场",
            size: 2,
            range_size: 0,
            color: "#000000",
            background_color: "#40E0D0",
            border_color: "#000000",
        },
        {
            name: "陶瓷场",
            text: "陶瓷场",
            size: 2,
            range_size: 0,
            color: "#000000",
            background_color: "#40E0D0",
            border_color: "#000000",
        },
        {
            name: "香料作坊",
            text: "香料作坊",
            size: 2,
            range_size: 0,
            color: "#000000",
            background_color: "#40E0D0",
            border_color: "#000000",
        },
        {
            name: "地毯作坊",
            text: "地毯作坊",
            size: 2,
            range_size: 0,
            color: "#000000",
            background_color: "#40E0D0",
            border_color: "#000000",
        },
        {
            name: "制糖厂",
            text: "制糖厂",
            size: 2,
            range_size: 0,
            color: "#000000",
            background_color: "#40E0D0",
            border_color: "#000000",
        },
        {
            name: "油坊",
            text: "油坊",
            size: 2,
            range_size: 0,
            color: "#000000",
            background_color: "#40E0D0",
            border_color: "#000000",
        },
        {
            name: "酒坊",
            text: "酒坊",
            size: 2,
            range_size: 0,
            color: "#000000",
            background_color: "#40E0D0",
            border_color: "#000000",
        },
    ],
    商业: [
        {
            name: "粮食货摊",
            text: "粮",
            size: 1,
            range_size: 5,
            color: "#000000",
            background_color: "#FFEC8B",
            border_color: "#000000",
        },
        {
            name: "蔬菜货摊",
            text: "菜",
            size: 1,
            range_size: 5,
            color: "#000000",
            background_color: "#FFEC8B",
            border_color: "#000000",
        },
        {
            name: "水果货摊",
            text: "果",
            size: 1,
            range_size: 5,
            color: "#000000",
            background_color: "#FFEC8B",
            border_color: "#000000",
        },
        {
            name: "生肉货摊",
            text: "肉",
            size: 1,
            range_size: 5,
            color: "#000000",
            background_color: "#FFEC8B",
            border_color: "#000000",
        },
        {
            name: "鱼虾货摊",
            text: "鱼",
            size: 1,
            range_size: 5,
            color: "#000000",
            background_color: "#FFEC8B",
            border_color: "#000000",
        },
        {
            name: "瓷器货摊",
            text: "瓷",
            size: 1,
            range_size: 5,
            color: "#000000",
            background_color: "#FFEC8B",
            border_color: "#000000",
        },
        {
            name: "香料货摊",
            text: "香",
            size: 1,
            range_size: 5,
            color: "#000000",
            background_color: "#FFEC8B",
            border_color: "#000000",
        },
        {
            name: "地毯货摊",
            text: "毯",
            size: 1,
            range_size: 5,
            color: "#000000",
            background_color: "#FFEC8B",
            border_color: "#000000",
        },
        {
            name: "糖品货摊",
            text: "糖",
            size: 1,
            range_size: 5,
            color: "#000000",
            background_color: "#FFEC8B",
            border_color: "#000000",
        },
        {
            name: "烟草货摊",
            text: "烟",
            size: 1,
            range_size: 5,
            color: "#000000",
            background_color: "#FFEC8B",
            border_color: "#000000",
        },
        {
            name: "芝麻油货摊",
            text: "油",
            size: 1,
            range_size: 5,
            color: "#000000",
            background_color: "#FFEC8B",
            border_color: "#000000",
        },
        {
            name: "葡萄酒货摊",
            text: "酒",
            size: 1,
            range_size: 5,
            color: "#000000",
            background_color: "#FFEC8B",
            border_color: "#000000",
        },
    ],
    市政: [
        {
            name: "饮水台",
            text: "水",
            size: 1,
            range_size: 4,
            color: "#000000",
            background_color: "#1E90FF",
            border_color: "#000000",
        },
        {
            name: "消防局",
            text: "消",
            size: 1,
            range_size: 6,
            color: "#000000",
            background_color: "#FF0000",
            border_color: "#000000",
        },
        {
            name: "维修站",
            text: "维",
            size: 1,
            range_size: 6,
            color: "#000000",
            background_color: "#FF0000",
            border_color: "#000000",
        },
        {
            name: "治安厅",
            text: "治",
            size: 1,
            range_size: 6,
            color: "#000000",
            background_color: "#FF0000",
            border_color: "#000000",
        },
        {
            name: "医疗站",
            text: "医疗",
            size: 2,
            range_size: 7,
            color: "#000000",
            background_color: "#FF0000",
            border_color: "#000000",
        },
        {
            name: "粮仓",
            text: "粮仓",
            size: 3,
            range_size: 0,
            color: "#000000",
            background_color: "#98F5FF",
            border_color: "#000000",
        },
        {
            name: "货栈",
            text: "货栈",
            size: 4,
            range_size: 0,
            color: "#000000",
            background_color: "#98F5FF",
            border_color: "#000000",
        },
        {
            name: "宫殿",
            text: "宫殿",
            size: 4,
            range_size: 0,
            color: "#000000",
            background_color: "#FFF68F",
            border_color: "#000000",
        },
        {
            name: "贸易站",
            text: "贸易站",
            size: 2,
            range_size: 0,
            color: "#000000",
            background_color: "#98F5FF",
            border_color: "#000000",
        },
        {
            name: "办公厅",
            text: "办公厅",
            size: 2,
            range_size: 6,
            color: "#000000",
            background_color: "#FF0000",
            border_color: "#000000",
        },
        {
            name: "水车房",
            text: "水车房",
            size: 2,
            range_size: 4,
            color: "#000000",
            background_color: "#C0FF3E",
            border_color: "#000000",
        },
        {
            name: "税务局",
            text: "税",
            size: 1,
            range_size: 4,
            color: "#000000",
            background_color: "#FF0000",
            border_color: "#000000",
        },
        {
            name: "磨坊",
            text: "磨坊",
            size: 1,
            range_size: 4,
            color: "#000000",
            background_color: "#C0FF3E",
            border_color: "#000000",
        },
        {
            name: "驿站",
            text: "驿站",
            size: 2,
            range_size: 0,
            color: "#000000",
            background_color: "#98F5FF",
            border_color: "#000000",
        },
    ],
    文化: [
        {
            name: "浴池",
            text: "浴池",
            size: 2,
            range_size: 8,
            color: "#000000",
            background_color: "#EEE8AA",
            border_color: "#000000",
        },
        {
            name: "斗兽场",
            text: "斗兽场",
            size: 4,
            range_size: 8,
            color: "#000000",
            background_color: "#EEDFCC",
            border_color: "#000000",
        },
        {
            name: "大学",
            text: "大学",
            size: 3,
            range_size: 8,
            color: "#000000",
            background_color: "#EED5B7",
            border_color: "#000000",
        },
        {
            name: "观星台",
            text: "观星台",
            size: 3,
            range_size: 8,
            color: "#000000",
            background_color: "#EEC900",
            border_color: "#000000",
        },
    ],
    宗教: [
        {
            name: "礼拜堂",
            text: "礼",
            size: 1,
            range_size: 6,
            color: "#000000",
            background_color: "#CDBA96",
            border_color: "#000000",
        },
        {
            name: "小清真寺",
            text: "小清真",
            size: 2,
            range_size: 8,
            color: "#000000",
            background_color: "#CD9B9B",
            border_color: "#000000",
        },
        {
            name: "大清真寺",
            text: "大清真寺",
            size: 4,
            range_size: 10,
            color: "#000000",
            background_color: "#CD8162",
            border_color: "#000000",
        },
    ],
    军事: [
        {
            name: "步兵兵营",
            text: "步兵",
            size: 2,
            range_size: 0,
            color: "#000000",
            background_color: "#CD5B45",
            border_color: "#000000",
        },
        {
            name: "射手兵营",
            text: "射手",
            size: 2,
            range_size: 0,
            color: "#000000",
            background_color: "#CD5555",
            border_color: "#000000",
        },
        {
            name: "骑兵兵营",
            text: "骑兵",
            size: 2,
            range_size: 0,
            color: "#000000",
            background_color: "#CD4F39",
            border_color: "#000000",
        },
        {
            name: "军事学院",
            text: "军事",
            size: 3,
            range_size: 0,
            color: "#000000",
            background_color: "#CD3700",
            border_color: "#000000",
        },
        {
            name: "武器铺",
            text: "武器铺",
            size: 2,
            range_size: 0,
            color: "#000000",
            background_color: "#CD3333",
            border_color: "#000000",
        },
        {
            name: "马厩",
            text: "马厩",
            size: 2,
            range_size: 0,
            color: "#000000",
            background_color: "#CD3278",
            border_color: "#000000",
        },
        {
            name: "象棚",
            text: "象棚",
            size: 3,
            range_size: 0,
            color: "#000000",
            background_color: "#CD3278",
            border_color: "#000000",
        },
    ],
    美化: [
        {
            name: "树",
            text: "树",
            size: 1,
            range_size: 0,
            color: "#000000",
            background_color: "#00FF7F",
            border_color: "#000000",
        },
    ],
    奇迹: [
        {
            name: "通天塔",
            text: "通天塔",
            size: 6,
            range_size: 0,
            color: "#000000",
            background_color: "#FFF68F",
            border_color: "#000000",
        },
        {
            name: "空中花园",
            text: "空中花园",
            size: 10,
            range_size: 0,
            color: "#000000",
            background_color: "#FFF68F",
            border_color: "#000000",
        },
    ],
    通用: [
        {
            name: "2x2建筑",
            text: "2x2",
            size: 2,
            range_size: 0,
            color: "#000000",
            background_color: "#87CEFF",
            border_color: "#000000",
        },
        {
            name: "3x3建筑",
            text: "3x3",
            size: 3,
            range_size: 0,
            color: "#000000",
            background_color: "#FF3E96",
            border_color: "#000000",
        },
        {
            name: "4x4建筑",
            text: "4x4",
            size: 4,
            range_size: 0,
            color: "#000000",
            background_color: "#E6E6FA",
            border_color: "#000000",
        },
        {
            name: "5x5建筑",
            text: "5x5",
            size: 5,
            range_size: 0,
            color: "#000000",
            background_color: "#AEEEEE",
            border_color: "#000000",
        },
    ],
};
