const BuildingAztaka = {
    住宅: [
        {
            name: "普通住宅",
            text: "宅",
            size: 1,
            range_size: 0,
            color: "#000000",
            background_color: "#FFA500",
            border_color: "#000000",
        },
        {
            name: "高级住宅",
            text: "高宅",
            size: 2,
            range_size: 0,
            color: "#000000",
            background_color: "#FFA500",
            border_color: "#000000",
        },
    ],
    农业: [
        {
            name: "玉米田",
            text: "玉米田",
            size: 3,
            range_size: 0,
            color: "#000000",
            background_color: "#32CD32",
            border_color: "#000000",
        },
        {
            name: "番茄园",
            text: "番茄园",
            size: 2,
            range_size: 0,
            color: "#000000",
            background_color: "#32CD32",
            border_color: "#000000",
        },
        {
            name: "牛油果园",
            text: "牛油果",
            size: 2,
            range_size: 0,
            color: "#000000",
            background_color: "#32CD32",
            border_color: "#000000",
        },
        {
            name: "狩猎小屋",
            text: "狩猎",
            size: 2,
            range_size: 0,
            color: "#000000",
            background_color: "#32CD32",
            border_color: "#000000",
        },
        {
            name: "可可园",
            text: "可可园",
            size: 2,
            range_size: 0,
            color: "#000000",
            background_color: "#32CD32",
            border_color: "#000000",
        },
        {
            name: "制羽小屋",
            text: "制羽小屋",
            size: 4,
            range_size: 0,
            color: "#000000",
            background_color: "#32CD32",
            border_color: "#000000",
        },
        {
            name: "烟草园",
            text: "烟草园",
            size: 2,
            range_size: 0,
            color: "#000000",
            background_color: "#32CD32",
            border_color: "#000000",
        },
        {
            name: "龙舌兰园",
            text: "龙舌兰园",
            size: 3,
            range_size: 0,
            color: "#000000",
            background_color: "#32CD32",
            border_color: "#000000",
        },
        {
            name: "仙人掌园",
            text: "仙人掌园",
            size: 3,
            range_size: 0,
            color: "#000000",
            background_color: "#32CD32",
            border_color: "#000000",
        },
        {
            name: "棉花园",
            text: "棉花园",
            size: 3,
            range_size: 0,
            color: "#000000",
            background_color: "#32CD32",
            border_color: "#000000",
        },
    ],
    工业: [
        {
            name: "陶器厂",
            text: "陶器厂",
            size: 2,
            range_size: 0,
            color: "#000000",
            background_color: "#40E0D0",
            border_color: "#000000",
        },
        {
            name: "纺织厂",
            text: "纺织厂",
            size: 2,
            range_size: 0,
            color: "#000000",
            background_color: "#40E0D0",
            border_color: "#000000",
        },
        {
            name: "雕刻厂",
            text: "雕刻厂",
            size: 2,
            range_size: 0,
            color: "#000000",
            background_color: "#40E0D0",
            border_color: "#000000",
        },
        {
            name: "染料场",
            text: "染料场",
            size: 2,
            range_size: 0,
            color: "#000000",
            background_color: "#40E0D0",
            border_color: "#000000",
        },
    ],
    商业: [
        {
            name: "粮店",
            text: "粮",
            size: 1,
            range_size: 5,
            color: "#000000",
            background_color: "#FFEC8B",
            border_color: "#000000",
        },
        {
            name: "蔬菜摊",
            text: "菜",
            size: 1,
            range_size: 5,
            color: "#000000",
            background_color: "#FFEC8B",
            border_color: "#000000",
        },
        {
            name: "水果摊",
            text: "果",
            size: 1,
            range_size: 5,
            color: "#000000",
            background_color: "#FFEC8B",
            border_color: "#000000",
        },
        {
            name: "肉铺",
            text: "肉",
            size: 1,
            range_size: 5,
            color: "#000000",
            background_color: "#FFEC8B",
            border_color: "#000000",
        },
        {
            name: "鱼摊",
            text: "鱼",
            size: 1,
            range_size: 5,
            color: "#000000",
            background_color: "#FFEC8B",
            border_color: "#000000",
        },
        {
            name: "陶器店",
            text: "陶",
            size: 1,
            range_size: 5,
            color: "#000000",
            background_color: "#FFEC8B",
            border_color: "#000000",
        },
        {
            name: "可可店",
            text: "可",
            size: 1,
            range_size: 5,
            color: "#000000",
            background_color: "#FFEC8B",
            border_color: "#000000",
        },
        {
            name: "龙舌兰酒",
            text: "酒",
            size: 1,
            range_size: 5,
            color: "#000000",
            background_color: "#FFEC8B",
            border_color: "#000000",
        },
        {
            name: "布匹轩",
            text: "布",
            size: 1,
            range_size: 5,
            color: "#000000",
            background_color: "#FFEC8B",
            border_color: "#000000",
        },
        {
            name: "染料货摊",
            text: "染",
            size: 1,
            range_size: 5,
            color: "#000000",
            background_color: "#FFEC8B",
            border_color: "#000000",
        },
        {
            name: "烟草店",
            text: "烟",
            size: 1,
            range_size: 5,
            color: "#000000",
            background_color: "#FFEC8B",
            border_color: "#000000",
        },
    ],
    市政: [
        {
            name: "水井",
            text: "水",
            size: 1,
            range_size: 4,
            color: "#000000",
            background_color: "#1E90FF",
            border_color: "#000000",
        },
        {
            name: "哨塔",
            text: "哨",
            size: 1,
            range_size: 6,
            color: "#000000",
            background_color: "#FF0000",
            border_color: "#000000",
        },
        {
            name: "维修站点",
            text: "维",
            size: 1,
            range_size: 6,
            color: "#000000",
            background_color: "#FF0000",
            border_color: "#000000",
        },
        {
            name: "医院",
            text: "医院",
            size: 2,
            range_size: 7,
            color: "#000000",
            background_color: "#FF0000",
            border_color: "#000000",
        },
        {
            name: "粮仓",
            text: "粮仓",
            size: 3,
            range_size: 0,
            color: "#000000",
            background_color: "#98F5FF",
            border_color: "#000000",
        },
        {
            name: "货栈",
            text: "货栈",
            size: 3,
            range_size: 0,
            color: "#000000",
            background_color: "#98F5FF",
            border_color: "#000000",
        },
        {
            name: "皇宫",
            text: "皇宫",
            size: 4,
            range_size: 0,
            color: "#000000",
            background_color: "#FFF68F",
            border_color: "#000000",
        },
        {
            name: "贸易站",
            text: "贸易站",
            size: 3,
            range_size: 0,
            color: "#000000",
            background_color: "#98F5FF",
            border_color: "#000000",
        },
        {
            name: "税务局",
            text: "税",
            size: 1,
            range_size: 4,
            color: "#000000",
            background_color: "#FF0000",
            border_color: "#000000",
        },
        {
            name: "大磨坊",
            text: "大磨坊",
            size: 2,
            range_size: 4,
            color: "#000000",
            background_color: "#C0FF3E",
            border_color: "#000000",
        },
        {
            name: "浇灌渠",
            text: "浇灌渠",
            size: 2,
            range_size: 4,
            color: "#000000",
            background_color: "#C0FF3E",
            border_color: "#000000",
        },
    ],
    文化: [
        {
            name: "预备学校",
            text: "预备",
            size: 2,
            range_size: 7,
            color: "#000000",
            background_color: "#EEE8AA",
            border_color: "#000000",
        },
        {
            name: "高等学校",
            text: "高等学校",
            size: 3,
            range_size: 8,
            color: "#000000",
            background_color: "#EEDFCC",
            border_color: "#000000",
        },
        {
            name: "专业学校",
            text: "专业学校",
            size: 4,
            range_size: 8,
            color: "#000000",
            background_color: "#EED5B7",
            border_color: "#000000",
        },
        {
            name: "蹴球场",
            text: "蹴球场",
            size: 4,
            range_size: 9,
            color: "#000000",
            background_color: "#EEC900",
            border_color: "#000000",
        },
        {
            name: "天文台",
            text: "天文台",
            size: 3,
            range_size: 10,
            color: "#000000",
            background_color: "#EEAEEE",
            border_color: "#000000",
        },
        {
            name: "植物园",
            text: "植物园",
            size: 6,
            range_size: 10,
            color: "#000000",
            background_color: "#EEAEEE",
            border_color: "#000000",
        },
    ],
    宗教: [
        {
            name: "祈雨神殿",
            text: "雨",
            size: 1,
            range_size: 5,
            color: "#000000",
            background_color: "#CDBA96",
            border_color: "#000000",
        },
        {
            name: "祭祀神殿",
            text: "祭祀",
            size: 2,
            range_size: 6,
            color: "#000000",
            background_color: "#CD9B9B",
            border_color: "#000000",
        },
        {
            name: "智慧神殿",
            text: "智慧神殿",
            size: 3,
            range_size: 8,
            color: "#000000",
            background_color: "#CD8162",
            border_color: "#000000",
        },
    ],
    军事: [
        {
            name: "步兵兵营",
            text: "步兵",
            size: 2,
            range_size: 0,
            color: "#000000",
            background_color: "#CD5B45",
            border_color: "#000000",
        },
        {
            name: "弩兵兵营",
            text: "弩兵",
            size: 2,
            range_size: 0,
            color: "#000000",
            background_color: "#CD5555",
            border_color: "#000000",
        },
        {
            name: "骑兵兵营",
            text: "骑兵兵营",
            size: 3,
            range_size: 0,
            color: "#000000",
            background_color: "#CD4F39",
            border_color: "#000000",
        },
        {
            name: "祭坛",
            text: "祭坛",
            size: 3,
            range_size: 0,
            color: "#000000",
            background_color: "#CD3700",
            border_color: "#000000",
        },
        {
            name: "武器铺",
            text: "武器铺",
            size: 2,
            range_size: 0,
            color: "#000000",
            background_color: "#CD3333",
            border_color: "#000000",
        },
        {
            name: "马厩",
            text: "马厩",
            size: 2,
            range_size: 0,
            color: "#000000",
            background_color: "#CD3278",
            border_color: "#000000",
        },
    ],
    美化: [
        {
            name: "树",
            text: "树",
            size: 1,
            range_size: 0,
            color: "#000000",
            background_color: "#00FF7F",
            border_color: "#000000",
        },
        {
            name: "城墙",
            text: "墙",
            size: 1,
            range_size: 0,
            color: "#FFFFFF",
            background_color: "#696A6B",
            border_color: "#000000",
        },
        {
            name: "城门",
            text: "门",
            size: 1,
            range_size: 0,
            color: "#000000",
            background_color: "#C06D2F",
            border_color: "#000000",
        },
    ],
    奇迹: [
        {
            name: "库库尔坎神庙",
            text: "库库尔坎神庙",
            size: 5,
            range_size: 0,
            color: "#000000",
            background_color: "#FFF68F",
            border_color: "#000000",
        },
        {
            name: "主神庙",
            text: "主神庙",
            size: 7,
            range_size: 0,
            color: "#000000",
            background_color: "#FFF68F",
            border_color: "#000000",
        },
        {
            name: "月亮金字塔",
            text: "月亮金字塔",
            size: 10,
            range_size: 0,
            color: "#000000",
            background_color: "#FFF68F",
            border_color: "#000000",
        },
        {
            name: "太阳金字塔",
            text: "太阳金字塔",
            size: 12,
            range_size: 0,
            color: "#000000",
            background_color: "#FFF68F",
            border_color: "#000000",
        },
    ],
    通用: [
        {
            name: "2x2建筑",
            text: "2x2",
            size: 2,
            range_size: 0,
            color: "#000000",
            background_color: "#87CEFF",
            border_color: "#000000",
        },
        {
            name: "3x3建筑",
            text: "3x3",
            size: 3,
            range_size: 0,
            color: "#000000",
            background_color: "#FF3E96",
            border_color: "#000000",
        },
        {
            name: "4x4建筑",
            text: "4x4",
            size: 4,
            range_size: 0,
            color: "#000000",
            background_color: "#E6E6FA",
            border_color: "#000000",
        },
        {
            name: "5x5建筑",
            text: "5x5",
            size: 5,
            range_size: 0,
            color: "#000000",
            background_color: "#AEEEEE",
            border_color: "#000000",
        },
    ],
};
